### ISSUE TITLE
Kaatuu

### ISSUE THREAD

**Issue by J45k4** [koodinikkarit/Taisto2#1]
emitter.emit("NEW_VIDEO_CONNECTION", String(conPort.id), String(cpuPort.id));
                                                                                       ^

TypeError: Cannot read property 'id' of undefined
    at EventEmitter.<anonymous> (/www/taistoreborn/backend/TaistoService.js:328:67)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at Socket.<anonymous> (/www/taistoreborn/backend/records/Matrix.js:135:45)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

**Comment by janhon3n** [comment]
Aika noloo

**Comment by J45k4** [comment]
?

**Comment by janhon3n** [comment]
Noloo et kaatuu
